// <auto-generated />
using System;
using Devsu.Customer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devsu.Customer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomerDbContext))]
    [Migration("20260904172423_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SeqClienteId")
                .StartsAt(4L);

            modelBuilder.Entity("Devsu.Customer.Domain.Entities.Persona", b =>
                {
                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("PersonaId");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasDatabaseName("UX_Personas_Identificacion");

                    b.ToTable("Personas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Personas_Edad", "[Edad] >= 0 AND [Edad] <= 150");

                            t.HasCheckConstraint("CK_Personas_Genero", "[Genero] IN ('Masculino','Femenino','Otro')");

                            t.HasCheckConstraint("CK_Personas_Identificacion", "LEN(LTRIM(RTRIM([Identificacion]))) >= 5");

                            t.HasCheckConstraint("CK_Personas_Nombre", "LEN(LTRIM(RTRIM([Nombre]))) > 0");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Devsu.Customer.Domain.Entities.Cliente", b =>
                {
                    b.HasBaseType("Devsu.Customer.Domain.Entities.Persona");

                    b.Property<DateTime?>("ActualizadoEn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreadoEn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("DesactivadoEn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasDatabaseName("UX_Clientes_ClienteId")
                        .HasFilter("[ClienteId] IS NOT NULL");

                    b.ToTable("Clientes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Personas_Edad", "[Edad] >= 0 AND [Edad] <= 150");

                            t.HasCheckConstraint("CK_Personas_Genero", "[Genero] IN ('Masculino','Femenino','Otro')");

                            t.HasCheckConstraint("CK_Personas_Identificacion", "LEN(LTRIM(RTRIM([Identificacion]))) >= 5");

                            t.HasCheckConstraint("CK_Personas_Nombre", "LEN(LTRIM(RTRIM([Nombre]))) > 0");

                            t.HasCheckConstraint("CK_Clientes_Credenciales", "LEN([PasswordHash]) >= 32 AND LEN([PasswordSalt]) >= 16");

                            t.HasCheckConstraint("CK_Clientes_Desactivacion", "([Estado] = 1 AND [DesactivadoEn] IS NULL) OR ([Estado] = 0 AND [DesactivadoEn] IS NOT NULL)");
                        });

                    b.HasData(
                        new
                        {
                            PersonaId = new Guid("019205a1-0001-7000-8000-000000000001"),
                            Direccion = "Otavalo sn y principal",
                            Edad = 35,
                            Genero = "Masculino",
                            Identificacion = "1712345678",
                            Nombre = "Jose Lema",
                            Telefono = "098254785",
                            ClienteId = "CLI-0001",
                            CreadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            PasswordHash = "x5pyxrT7ryEiPc7V/TXeJajxvCjZRp3HomB8Xytn2J0=",
                            PasswordSalt = "ej8cjlsgTZeh5sBLPY8hWQ=="
                        },
                        new
                        {
                            PersonaId = new Guid("019205a1-0001-7000-8000-000000000002"),
                            Direccion = "Amazonas y NNUU",
                            Edad = 29,
                            Genero = "Femenino",
                            Identificacion = "0923456789",
                            Nombre = "Marianela Montalvo",
                            Telefono = "097548965",
                            ClienteId = "CLI-0002",
                            CreadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            PasswordHash = "2SYFs5GQexixZOfaJCK4HyDWVKMCziJganfyvB2mQvU=",
                            PasswordSalt = "LptNB8GjSG+1DX4pRqyBNw=="
                        },
                        new
                        {
                            PersonaId = new Guid("019205a1-0001-7000-8000-000000000003"),
                            Direccion = "13 junio y Equinoccial",
                            Edad = 42,
                            Genero = "Masculino",
                            Identificacion = "1804567890",
                            Nombre = "Juan Osorio",
                            Telefono = "098874587",
                            ClienteId = "CLI-0003",
                            CreadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            PasswordHash = "O2pH5ri6pKmukgDnNKyhgpLOouFV1WDq/NUfkpegyYw=",
                            PasswordSalt = "xI1fGgt+QmOa2BL15wO8ag=="
                        });
                });

            modelBuilder.Entity("Devsu.Customer.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("Devsu.Customer.Domain.Entities.Persona", null)
                        .WithOne()
                        .HasForeignKey("Devsu.Customer.Domain.Entities.Cliente", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
