// <auto-generated />
using System;
using Devsu.Account.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Devsu.Account.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AccountDbContext))]
    partial class AccountDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Devsu.Account.Domain.Entities.ClienteReplica", b =>
                {
                    b.Property<string>("ClienteId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("ActualizadoEn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ClienteId");

                    b.ToTable("ClientesReplica", (string)null);

                    b.HasData(
                        new
                        {
                            ClienteId = "CLI-0001",
                            ActualizadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Identificacion = "1712345678",
                            Nombre = "Jose Lema"
                        },
                        new
                        {
                            ClienteId = "CLI-0002",
                            ActualizadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Identificacion = "0923456789",
                            Nombre = "Marianela Montalvo"
                        },
                        new
                        {
                            ClienteId = "CLI-0003",
                            ActualizadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            Identificacion = "1804567890",
                            Nombre = "Juan Osorio"
                        });
                });

            modelBuilder.Entity("Devsu.Account.Domain.Entities.Cuenta", b =>
                {
                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClienteId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreadoEn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SaldoDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("CuentaId");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IX_Cuentas_ClienteId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ClienteId"), new[] { "NumeroCuenta", "TipoCuenta", "SaldoInicial", "SaldoDisponible", "Estado" });

                    b.HasIndex("NumeroCuenta")
                        .IsUnique()
                        .HasDatabaseName("UX_Cuentas_NumeroCuenta");

                    b.ToTable("Cuentas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cuentas_SaldoDisponible", "[SaldoDisponible] >= 0");

                            t.HasCheckConstraint("CK_Cuentas_SaldoInicial", "[SaldoInicial] >= 0");

                            t.HasCheckConstraint("CK_Cuentas_TipoCuenta", "[TipoCuenta] IN ('Ahorros','Corriente')");
                        });

                    b.HasData(
                        new
                        {
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000001"),
                            ClienteId = "CLI-0001",
                            CreadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            NumeroCuenta = "478758",
                            SaldoDisponible = 1425.00m,
                            SaldoInicial = 2000.00m,
                            TipoCuenta = "Ahorros"
                        },
                        new
                        {
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000002"),
                            ClienteId = "CLI-0002",
                            CreadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            NumeroCuenta = "225487",
                            SaldoDisponible = 700.00m,
                            SaldoInicial = 100.00m,
                            TipoCuenta = "Corriente"
                        },
                        new
                        {
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000003"),
                            ClienteId = "CLI-0003",
                            CreadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            NumeroCuenta = "495878",
                            SaldoDisponible = 150.00m,
                            SaldoInicial = 0.00m,
                            TipoCuenta = "Ahorros"
                        },
                        new
                        {
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000004"),
                            ClienteId = "CLI-0002",
                            CreadoEn = new DateTime(2022, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            NumeroCuenta = "496825",
                            SaldoDisponible = 0.00m,
                            SaldoInicial = 540.00m,
                            TipoCuenta = "Ahorros"
                        },
                        new
                        {
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000005"),
                            ClienteId = "CLI-0001",
                            CreadoEn = new DateTime(2022, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Estado = true,
                            NumeroCuenta = "585545",
                            SaldoDisponible = 1000.00m,
                            SaldoInicial = 1000.00m,
                            TipoCuenta = "Corriente"
                        });
                });

            modelBuilder.Entity("Devsu.Account.Domain.Entities.EventoProcesado", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ProcesadoEn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("EventId");

                    b.HasIndex("ProcesadoEn")
                        .HasDatabaseName("IX_EventosProcesados_ProcesadoEn");

                    b.ToTable("EventosProcesados", (string)null);
                });

            modelBuilder.Entity("Devsu.Account.Domain.Entities.Movimiento", b =>
                {
                    b.Property<Guid>("MovimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Fecha")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("RegistradoEn")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MovimientoId");

                    b.HasIndex("CuentaId", "Fecha")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Movimientos_CuentaId_Fecha");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CuentaId", "Fecha"), new[] { "TipoMovimiento", "Valor", "Saldo" });

                    b.ToTable("Movimientos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Movimientos_SaldoNoNegativo", "[Saldo] >= 0");

                            t.HasCheckConstraint("CK_Movimientos_Tipo", "[TipoMovimiento] IN ('Deposito','Retiro')");

                            t.HasCheckConstraint("CK_Movimientos_TipoCoherente", "([Valor] > 0 AND [TipoMovimiento] = 'Deposito') OR ([Valor] < 0 AND [TipoMovimiento] = 'Retiro')");

                            t.HasCheckConstraint("CK_Movimientos_ValorNoCero", "[Valor] <> 0");
                        });

                    b.HasData(
                        new
                        {
                            MovimientoId = new Guid("019205a3-0001-7000-8000-000000000001"),
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000004"),
                            Fecha = new DateTime(2022, 2, 8, 10, 15, 0, 0, DateTimeKind.Utc),
                            RegistradoEn = new DateTime(2022, 2, 8, 10, 15, 0, 0, DateTimeKind.Utc),
                            Saldo = 0.00m,
                            TipoMovimiento = "Retiro",
                            Valor = -540.00m
                        },
                        new
                        {
                            MovimientoId = new Guid("019205a3-0001-7000-8000-000000000002"),
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000001"),
                            Fecha = new DateTime(2022, 2, 9, 9, 30, 0, 0, DateTimeKind.Utc),
                            RegistradoEn = new DateTime(2022, 2, 9, 9, 30, 0, 0, DateTimeKind.Utc),
                            Saldo = 1425.00m,
                            TipoMovimiento = "Retiro",
                            Valor = -575.00m
                        },
                        new
                        {
                            MovimientoId = new Guid("019205a3-0001-7000-8000-000000000003"),
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000002"),
                            Fecha = new DateTime(2022, 2, 10, 11, 45, 0, 0, DateTimeKind.Utc),
                            RegistradoEn = new DateTime(2022, 2, 10, 11, 45, 0, 0, DateTimeKind.Utc),
                            Saldo = 700.00m,
                            TipoMovimiento = "Deposito",
                            Valor = 600.00m
                        },
                        new
                        {
                            MovimientoId = new Guid("019205a3-0001-7000-8000-000000000004"),
                            CuentaId = new Guid("019205a2-0001-7000-8000-000000000003"),
                            Fecha = new DateTime(2022, 2, 11, 14, 20, 0, 0, DateTimeKind.Utc),
                            RegistradoEn = new DateTime(2022, 2, 11, 14, 20, 0, 0, DateTimeKind.Utc),
                            Saldo = 150.00m,
                            TipoMovimiento = "Deposito",
                            Valor = 150.00m
                        });
                });

            modelBuilder.Entity("Devsu.Account.Domain.Entities.Movimiento", b =>
                {
                    b.HasOne("Devsu.Account.Domain.Entities.Cuenta", null)
                        .WithMany("Movimientos")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Devsu.Account.Domain.Entities.Cuenta", b =>
                {
                    b.Navigation("Movimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
